# https://taskfile.dev

version: "3"

dotenv: [".env"]

tasks:
  init:
    cmds:
      - poetry install
  lint:
    cmds:
      - poetry run pylint --rcfile pylintrc .
      - poetry run mypy rabbit
      - poetry run ruff check rabbit
      - poetry run ruff format --check rabbit
  lint-diff:
    cmds:
      - poetry run ruff format --diff rabbit
  format:
    cmds:
      - poetry run black --line-length 120 .
      - poetry run ruff check --fix
  prod:
    cmds:
      - poetry run waitress-serve --port=$PORT_NUMBER --call gateway.flask.factory:create_flask_app
  build-dev:
    cmds:
      - docker build -t andrewli2048/rabbit-backend -f docker/DevDockerfile .
  run-dev:
    cmds:
      - task: build-dev
      - docker run --rm -p 9000:9000 --name rabbit-backend andrewli2048/rabbit-backend
  build-prod:
    cmds:
      - docker build -t andrewli2048/rabbit-backend -f docker/ProdDockerfile .
      - docker push andrewli2048/rabbit-backend
  run-prod:
    cmds:
      - task: build-prod
      - docker run --rm -p 9000:9000 --name rabbit-backend-prod andrewli2048/rabbit-backend
